from dataclasses import dataclass, field
from typing import Any, List, Optional
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

@dataclass
class AgentResponse:
    """
    Represents the structured result of an interaction with an agent.

    Attributes:
        text (str): The final text response generated by the agent.
        events (List[Any]): A collection of all execution events yielded during the 
            interaction, including tool calls, internal thoughts, and status updates.
    """
    text: str
    events: List[Any] = field(default_factory=list)

class AgentBroker:
    """
    Broker to interact with an ADK Agent.
    """
    def __init__(self, agent: Any):
        self.agent = agent
        self.session_service = InMemorySessionService()
        self.app_name = "AgentBrokerApp"
        self.user_id = "default_user"
        self.session_id = "default_session"
        self.runner = Runner(
            agent=self.agent,
            app_name=self.app_name,
            session_service=self.session_service
        )
        self._session_initialized = False

    async def interact(self, message: str) -> AgentResponse:
        """
        Feeds text message to the agent and returns the final response.
        """
        if not self._session_initialized:
            await self.session_service.create_session(
                app_name=self.app_name,
                user_id=self.user_id,
                session_id=self.session_id
            )
            self._session_initialized = True

        user_content = types.Content(
            role='user',
            parts=[types.Part(text=message)]
        )

        final_text = ""
        interaction_events = []
        async for event in self.runner.run_async(
            user_id=self.user_id,
            session_id=self.session_id,
            new_message=user_content
        ):
            interaction_events.append(event)
            if event.is_final_response() and event.content and event.content.parts:
                final_text = event.content.parts[0].text

        return AgentResponse(text=final_text, events=interaction_events)
